#%RAML 1.0 Library

types:
  entityCore:
    type: object
    properties:
      state:
        type: string
      version:
        type: number
      createdOn:
        type: date
      updatedOn:
        type: date
      createdBy:
        type: string
      updatedBy:
        type: string 