#%RAML 1.0 Library

types:
  entityCore:
    type: object
    properties:
      state:
        type: string
      version:
        type: number
      createdOn:
        type: datetime
      updatedOn:
        type: datetime
      createdBy:
        type: string
        required: false
      updatedBy:
        type: string 
        required: false
    
  period:
    type: object
    properties:
      startDate:
        type: date-only
      endDate:
        type: date-only
  