#%RAML 1.0 Trait

queryParameters:
    offset:
      description: Skip over the number of elements by specifying an offset value.
      type: integer
      required: false
      example: 50
      default: 0
    limit:
      description: Limit the number of elements to return in the response.
      type: integer
      required: false
      example: 100
      default: 100
      